export const OPEN_MODAL_MENU = 'OPEN_MODAL_MENU';
export const CLOSE_MODAL_MENU = 'CLOSE_MODAL_MENU';
export const SET_ACTIVE_PRICE_TABLE = 'SET_ACTIVE_PRICE_TABLE';
export const GET_ORDER_FORM_DATA = 'GET_ORDER_FORM_DATA';
export const IS_IMAGE_LOADING = 'IS_IMAGE_LOADING';